name: P3B_Estudillos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flame: ^1.26.1
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bullet.png
    - assets/images/enemy.png
    - assets/images/explosion.png
    - assets/images/player.png
    - assets/images/stars.png
    - assets/images/gorila.png
    - assets/images/platano.png
    - assets/images/frieren.png
